---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by test.
--- DateTime: 2021/4/7 下午2:47
---Lua 协同程序(coroutine)

co = coroutine.create(
        function(i)
            print(i);
        end
)


function foo (a)
    print("foo 函数输出", a)
    return coroutine.yield(2 * a) -- 返回  2*a 的值
end

co = coroutine.create(function (a , b)
    print("第一次协同程序执行输出", a, b) -- co-body 1 10
    local r = foo(a + 1)

    print("第二次协同程序执行输出", r)
    local r, s = coroutine.yield(a + b, a - b)  -- a，b的值为第一次调用协同程序时传入

    print("第三次协同程序执行输出", r, s)
    return b, "结束协同程序"                   -- b的值为第二次调用协同程序时传入
end)
--yield() :	挂起 coroutine
--resume()：重启 coroutine，和 create 配合使用
--wrap（）: 创建 coroutine，返回一个函数，一旦你调用这个函数，就进入 coroutine
print("main", coroutine.resume(co, 1, 10)) -- true, 4
print("--分割线1----")

print("main", coroutine.resume(co, "r")) -- true 11 -9
print("---分割线2---")

print("main", coroutine.resume(co, "x", "y")) -- true 10 end
print("---分割线---")























