---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by test.
--- DateTime: 2021/4/6 下午2:53
---

function addNum( num1 , num2 )

    print( num1 , num2 );

    return num1 + num2 , num2 * num1;

end

function printNum()
    result ,result2  = addNum( 2 , 3 );
    print( result   );
    print( result2   );
end



function for1Circle()
    array = {"Lua", "Tutorial"}

    for i= 0, 2 do
        print(array[i])
    end

end

--printNum(  );
--for1Circle()

mytable = {}
print("mytable 的类型是 ",type(mytable))

mytable[1]= "Lua"
mytable["wow"] = "修改前"
print("mytable 索引为 1 的元素是 ", mytable[1])
print("mytable 索引为 wow 的元素是 ", mytable["wow"])
















